### ISSUE TITLE
Add a workflow to build the gateway program as a check before merging a PR

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/protocol-contracts-solana#17]
Prevents merging code that doesn't compile.

**Comment by brewmaster012** [comment]
and also run the anchor test command (integration test on a local validator)  in addition to cargo test (unit tests in program)

**Comment by lumtis** [comment]
Original issue should be solved as we added cargo test in the CI

Opening a separate issue for the integration test: https://github.com/zeta-chain/protocol-contracts-solana/issues/44
