### ISSUE TITLE
Gateway refund SOL tx fee to the payer

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/protocol-contracts-solana#4]
Currently the signers of the outbound tx (relayer) pays tx fee on Solana. 
They should be reimbursed of the tx fee (~5000 lamports) if the relayed tx is successful. 
This removes operation burden of relayer and remove the negative incentives for them.

**Comment by lumtis** [comment]
Closing for now, we need description for each opened issue to understand context of these
